# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'help.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("send message")
        Form.resize(273, 376)
        self.name_label = QtWidgets.QLabel(Form)
        self.name_label.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.name_label.setObjectName("name_label")
        self.name_input = QtWidgets.QLineEdit(Form)
        self.name_input.setGeometry(QtCore.QRect(10, 30, 201, 21))
        self.name_input.setObjectName("name_input")
        self.issue_label = QtWidgets.QLabel(Form)
        self.issue_label.setGeometry(QtCore.QRect(10, 60, 91, 16))
        self.issue_label.setObjectName("issue_label")
        self.issue_input = QtWidgets.QTextEdit(Form)
        self.issue_input.setGeometry(QtCore.QRect(10, 80, 241, 111))
        self.issue_input.setObjectName("issue_input")
        self.email_label = QtWidgets.QLabel(Form)
        self.email_label.setGeometry(QtCore.QRect(10, 200, 201, 16))
        self.email_label.setObjectName("email_label")
        self.email_input = QtWidgets.QLineEdit(Form)
        self.email_input.setGeometry(QtCore.QRect(10, 220, 201, 21))
        self.email_input.setObjectName("email_input")
        self.send = QtWidgets.QPushButton(Form)
        self.send.setGeometry(QtCore.QRect(0, 290, 121, 51))
        self.send.setObjectName("send")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 290, 121, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 250, 301, 31))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("color:red")
        self.label.setText("")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.name_label.setText(_translate("Form", "name"))
        self.issue_label.setText(_translate("Form", "describe the issue:"))
        self.email_label.setText(_translate("Form", "your email (not required):"))
        self.send.setText(_translate("Form", "send"))
        self.pushButton_2.setText(_translate("Form", "cancel"))
